version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: raspi_backend
    volumes:
      - ./backend:/app
    working_dir: /app
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    command: ["air"]

  db:
    image: postgres:15-alpine
    container_name: raspi_db
    environment:
      POSTGRES_DB: raspi
      POSTGRES_USER: raspi_user
      POSTGRES_PASSWORD: raspi_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

