services:
  # ===================================
  # フロントエンドサービス（Nginx + React）
  # ===================================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: raspi_frontend
    ports:
      # ホストの3000番ポートをコンテナの80番ポートにマッピング
      - "3000:80"
    depends_on:
      - backend
    networks:
      - backend_net
    # ヘルスチェック設定
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # ===================================
  # バックエンドサービス（Go + Gin）
  # ===================================
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: raspi_backend
    working_dir: /app
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - backend_net

  db:
    image: postgres:15-alpine
    container_name: raspi_db
    environment:
      POSTGRES_DB: raspi
      POSTGRES_USER: raspi_user
      POSTGRES_PASSWORD: raspi_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend_net

  migrate:
    image: migrate/migrate
    volumes:
      - ./backend/migrations:/migrations
    depends_on:
      - db
    networks:
      - backend_net

  seed:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: builder
    working_dir: /app
    command: go run internal/seed/main.go
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - backend_net

volumes:
  pgdata:

networks:
  backend_net:
