name: device_platform
services:
  app:
    image: ghcr.io/tomitahisaki/device-platform-backend:${IMAGE_TAG:-stable}
    env_file: [ ./.env.prod ]
    ports: ["127.0.0.1:3000:3000"]
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:16
    env_file:
      - ./.env.prod
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-myapp} -d ${POSTGRES_DB:-myapp}",
        ]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped
    secrets:
      - pg_password

  migrator:
    image: migrate/migrate:4
    volumes: 
      - ./migrations:/migrations
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env.prod
    entrypoint: ["sh","-c"]
    command: >
      DB_URL="postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT:-5432}/${DB_NAME}?sslmode=disable"
      && migrate -path=/migrations -database "$DB_URL" up

secrets:
  pg_password:
    file: ./secrets/pg_password

volumes:
  pgdata:
