services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod # ← 本番用を明示
    env_file:
      - ./.env # ← サーバだけにある .env を読む
    ports:
      - "127.0.0.1:3000:3000" # 外部直アクセス不可（Nginxのみ可）
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-myapp}
      POSTGRES_DB: ${POSTGRES_DB:-myapp}
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-myapp} -d ${POSTGRES_DB:-myapp}",
        ]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped
    secrets:
      - pg_password

secrets:
  pg_password:
    file: ./secrets/pg_password

volumes:
  pgdata:
