name: Backend CI

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/frontend-ci.yml" # Only run on changes to frontend or CI config
  pull_request:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/frontend-ci.yml" # Only run on changes to frontend or CI config

jobs:
  build:
    name: Run frontend ci
    runs-on: ubuntu-latest
    workintg-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint
